#pragma kernel BoidsCompute

struct BoidAgent
{
    float3 position;
    float2 velocity;
    float3 target;
    float maxSpeed;
};

RWStructuredBuffer<BoidAgent> boids;

int agentCount;
float deltaTime;


[numthreads(256,1,1)]
void BoidsCompute (uint3 id : SV_DispatchThreadID)
{
    uint index = id.x;
    if (index >= agentCount) return;
    
    BoidAgent agent = boids[index];
    
    float3 toTarget = agent.target - agent.position;
    float distance = length(toTarget);
    
    if (distance > 0.1)
    {
        float2 desired = normalize(toTarget) * agent.maxSpeed;
        agent.velocity = lerp(agent.velocity, desired, 0.05);
    } else
    {
        agent.velocity = float2(0.0 , 0.0 );
    }
    
    agent.position += agent.velocity * deltaTime;
    
    boids[index] = agent;
}
